t = input("Enter cells:")
print("---------")
print("| " + t[0] + ' ' + t[1] + ' ' + t[2] + " |")
print("| " + t[3] + ' ' + t[4] + ' ' + t[5] + " |")
print("| " + t[6] + ' ' + t[7] + ' ' + t[8] + " |")
print("---------")
